---
apiVersion: v1
kind: Secret
metadata:
  name: kube-nova-secret
  namespace: kube-nova
type: Opaque
stringData:
  # 全局超时
  DEFAULT_TIMEOUT: "30000"

  # MySQL 基础参数
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "kube_nova"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "8VlZ2lvIsKBCYSE3"
  MYSQL_MAX_OPEN_CONNS: "100"
  MYSQL_MAX_IDLE_CONNS: "50"
  MYSQL_CONN_MAX_LIFETIME: "30m"

  # Redis 基础参数
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "2VOSiz0vhGtxaBJb"
  REDIS_TYPE: "node"
  REDIS_TLS: "false"
  REDIS_NONBLOCK: "true"
  REDIS_PING_TIMEOUT: "3s"

  # MinIO 配置
  MINIO_ENDPOINT: "minio-service:9000"
  MINIO_ACCESS_KEY: "kube-nova-admin"
  MINIO_SECRET_KEY: "KubeNova@2024SecretKey!"
  MINIO_BUCKET: "kube-nova"
  MINIO_USE_TLS: "false"

  # JWT
  JWT_ACCESS_SECRET: "zk5Lp8m+0g7lvvLcnbUHPzQFEsRAmvNIn9tXdx0o80U="
  JWT_ACCESS_EXPIRE: "86400"
  JWT_REFRESH_SECRET: "zk5Lp8m+0g7lvvLcnbUHPzQFEsRAmvNIn9tXdx0o80U="
  JWT_REFRESH_EXPIRE: "604800"
  JWT_REFRESH_AFTER: "604800"

  # Webhook
  ALERTMANAGER_WEBHOOK_TOKEN: "mRwErqZaQVrxfyhiDQrdiQohAsONwSTtwhcmFXpCcaGavcINqorVoWINnSFFAijb"

  # Jaeger
  JAEGER_ENDPOINT: "http://jaeger-collector:14268/api/traces"
  TELEMETRY_SAMPLER: "1.0"
  TELEMETRY_BATCHER: "jaeger"

  # Portal
  PORTAL_NAME: "Kube-Nova 云原生平台"
  PORTAL_URL: "http://www.yanshicheng.com:8888"
  DEMO_MODE: "true"

  # 其他
  INJECT_IMAGE: "harbor.ikubeops.local/public/network-multitool:latest"