---
apiVersion: v1
kind: Service
metadata:
  name: console-api
  namespace: kube-nova
spec:
  type: ClusterIP
  selector:
    app: console-api
  ports:
    - name: http
      port: 8818
      targetPort: 8818

