---
apiVersion: v1
kind: Service
metadata:
  name: portal-rpc
  namespace: kube-nova
spec:
  type: ClusterIP
  selector:
    app: portal-rpc
  ports:
    - name: http
      port: 30010
      targetPort: 30010

