---
apiVersion: v1
kind: Service
metadata:
  name: portal-api
  namespace: kube-nova
spec:
  type: ClusterIP
  selector:
    app: portal-api
  ports:
    - name: http
      port: 8810
      targetPort: 8810
